project:
  type: book
  output-dir: docs

book:
  title: "scOmicNotes"
  author: "Kevin Z. Lin"
  date: "7/14/2025"
  chapters:
    - index.qmd
    - chapter1_intro.qmd
    - chapter2_sequencing.qmd
    - chapter3_rna.qmd
    - chapter4_protein.qmd
    - chapter5_epigenetics.qmd
    - chapter8_lineage.qmd
    - references.qmd

bibliography: references.bib

resources:
  - fig           # tells Quarto to copy everything under fig/ into _site/

format:
  html:
    number-sections: true
    toc: true
    theme:
      - cosmo
      - brand
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: visual

